#!/bin/bash

param=" "

if [[ -f "$@" ]];
then
	if [[ $param = *[!\ ]* ]];
	then
		sed 's/ \+ /\t/g' $@ >> tmp
	else
		sed 's/ \+ //g' $@ >> tmpmv tmp $@
	fi
	mv tmp $@

elif [[ -z "$@" ]];
then
	echo "Error : no file passed"
	exit -2
else
	echo "Error : $@ is not a file"
	exit -1
fi
