#!/bin/bash

if [[ -f "$@" ]];
then
	#sed 's/ \+ /\t/g' $@ > tmp
	while IFS= read -r line; do
		tr -cd ' \t' | wc -c
	sed -e 's/    /\t/g' $@ > new
elif [[ -z "$@" ]];
then
	echo "Error : no file passed"
	exit -2
else
	echo "Error : $@ is not a file"
	exit -1
fi
