#!/bin/bash

if [[ -f $@ ]];
then
	now=$(date +"%m_%d_%Y")
	tnow=$(date +"%T")
	tar -czf trash/"f"$now":"$tnow "$@" --remove-file
elif [[ -d $@ ]];
then
	echo "Cannot delete file: $@ is a directory"
fi
