#!/bin/bash
# Create a README file without opening text editor

if [ -z "$1" ]
then
	if [[ -e ./README.md ]]
	then
		ls | while read f;
	do
		if grep -q "$f" "./README.md";
		then
			continue
		else
			echo "> $f" >> README.md
		fi
		if [ $verbose ];
		then
			echo "README file modified"
		fi
		exit 0
	done
	else
	if [ $verbose ];
	then
		echo "No arguments supplied"
	fi
	ls -R -1 | while read f;
	do
		echo " > $f" >> README.md
	done
	exit 0
	fi

else
	while getopts "t:w:f:hqadD" opt; do
		case $opt in
			t)
			touch README.md
			title=$OPTARG
			sed -i "1s/^/\# \*\*$title\*\*\n/" README.md;;
			w)
			touch README.md
			desc=$OPTARG
			line=$(head -n 1 README.md)
			if grep -q $title $line
			then
				sed -i "2s/^/$desc\n/" README.md
			else
				sed -i "1s/^/$desc\n/"
			fi;;
			h) cat ./help_mkrm
			exit 1 ;;
			q) verbose=$(false) ;;
			a) ls -R -X -A| while read f;
			do
				echo "> $f" >> README.md
			done;;
			d) ls -R -t -A | while read f;
			do
				echo "> $f" >> README.md
			done;;
			D) ls -R -t -r -A | while read f;
			do
				echo "> $f" >> README.md
			done;;
			f) filename=$OPTARG
				echo $filename >> README.md
				touch $filename;;
			\?) echo "$i: unknown flag" ;;
	esac
done
fi

if [[ -e ./README.md ]]
then
	if [ $verbose ]
	then
		echo "README file created"
	fi
	exit 0
else
	echo "Error: README file could not be created."
	date +"%x %X" >> error_log
	echo "$0: README file could not be created." >> error_log
	exit -1
fi
#echo -n $desc | cat README.md > README.md ;;
