#!/bin/bash
# Create a README file without opening text editor

if [ -z "$1" ]
then
	if [[ -e ./README.md ]]
	then
		ls -R -1 -A | while read f;
	do
		if grep -q "$f" "./README.md";
		then
			continue
		else
			echo "- $f" >> README.md
		fi
		if [ $verbose ];
		then
			echo "README file modified"
		fi
		exit 0
	done
	else
	if [ $verbose ];
	then
		echo "No arguments supplied"
	fi
	ls -R -1 -A | while read f;
	do
		echo " - $f" >> README.md
	done
	exit 0
	fi

else
	if [[ -e ./README.md ]]
	then
		while getopts "f:hq" opt; do
			case $opt in
				f)
					filename=$OPTARG
					echo "- $filename" >> README.md
					touch $filename;;
				h)
					cat ./help_mkrm
					exit 1;;
				q)
					verbose=$(false) ;;
				\?)
					echo "Invalide flags: for more informations 'mkrm -h'"
			esac
		done
		if [ $verbose ];
		then
			echo "README file modified"
		fi
	else
		while getopts "t:w:f:hqadD" opt; do
			case $opt in
				t)
				touch README.md
				title=$OPTARG
				if [ ! -s "README.md" ];
				then
					echo "# **$title**" > README.md
				else
					cat README.md >> tmp
					echo "# **$title**" > README.md
					cat tmp >> README.md
					rm -f tmp
				fi;;
				w)
				touch README.md
				desc=$OPTARG
				line=$(head -n 1 README.md)
				if [[ "$line" == "> " ]]
				then
					cat README.md > tmp
					echo "$desc" > README.md
					cat tmp >> README.md
					rm -f tmp
				elif [ ! -s "README.md" ];
				then
					echo "$desc" > README.md
				else
					head -n 2 README.md | echo "$desc" >> README.md
				fi;;
				h)
					cat /home/working_helper/wrk_environment_setter/help_mkrm
					exit 1 ;;
				q) verbose=$(false) ;;
				a)
					ls -R -X -A| while read f;
				do
					echo "- $f" >> README.md
				done;;
				d) ls -R -t -A | while read f;
				do
					echo "- $f" >> README.md
				done;;
				D) ls -R -t -r -A | while read f;
				do
					echo "- $f" >> README.md
				done;;
				f) filename=$OPTARG
					echo "- $filename" >> README.md
					touch $filename;;
				\?) echo "$i: unknown flag" ;;
			esac
		done
	fi
		ls -R -1 -A | while read f;
	do
		if grep -q "$f" "./README.md" ;
		then
			continue
		else
			echo "- $f" >> README.md
		fi
	done
fi

if [[ -e ./README.md ]]
then
	if [ $verbose ]
	then
		echo "README file created"
	fi
	exit 0
else
	echo "Error: README file could not be created."
	date +"%x %X" >> error_log
	echo "$0: README file could not be created." >> error_log
	exit -1
fi
