#!/bin/bash
# Create a README file without opening text editor

verbose=$(false)

if [ -z "$1" ]
then
	if [[ -e ./README.md ]]
	then
		ls | while read f;
	do
		if grep -q "$f" "./README.md";
		then
			continue
		else
			echo "$f" >> README.md
		fi
		if [ $verbose ];
		then
			echo "README file modified"
		fi
		exit 0
	done
	else
	if [ $verbose ];
	then
		echo "No arguments supplied"
	fi
	ls | while read f;
	do
		echo $f >> README.md
	done
	exit 0
	fi

else
	while getopts "hvadDf" opt; do
		#elif [[ "$i" == ^- ]];
		#then
	case $opt in
		h) cat ./help_mkrm
			exit 1 ;;
		v) verbose=$(true) ;;
		a) ls -R -X >> README.md 
			exit 0 ;;
		d) ls -R -t >> README.md 
			exit 0 ;;
		D) ls -R -t -r >> README.md 
			exit 0;;
		f) filename=$OPTARG ;;
		\?) echo "$i: unknown flag" ;;
	esac
done
	echo -e "$i $(cat README.md)" > README.md
	ls -1 -R >> README.md
fi

if [[ -e ./README.md ]]
then
	if [ $verbose ]
	then
		echo "README file created"
	fi
	exit 0
else
	echo "Error: README file could not be created."
	date +"%x %X" >> error_log
	echo "$0: README file could not be created." >> error_log
	exit -1
fi
