#!/bin/bash
# Delete files or directory (more secured than rm)

if [[ -z "$1" ]]; then
	echo "dl: arguments missing"
	echo "dl -h for help"
	exit 1
else
	for i in $*; do
		if [[ $i == *-h* ]]; then
			cat /home/working_helper/wrk_environment_setter/DLT/dl_help
			exit 0

		else
			if [[ -d $i ]]; then
				bash ./del_dir $i
			else
				bash ./del_fl $i
			fi
		fi
	done
fi

if [[ "$?" -ne 0 ]];
then
	echo "Error: File(s) could not be deleted."
	date +"%x %X" >> /home/working_helper/wrk_environment_setter/ERR/error_log
	echo "$0: File(s) could not be deleted." >> /home/working_helper/wrk_environment_setter/ERR/error_log
	exit -1
fi
